variable "name" {
  type        = string
  description = "Name of the VPN"
}

variable "vpn_saml_metadata" {
  type        = string
  description = "VPN XML document generated by an identity provider that supports SAML 2.0."
}

variable "vpn_portal_saml_metadata" {
  type        = string
  description = "VPN SelfService Portal XML document generated by an identity provider that supports SAML 2.0."
}

variable "tags" {
  description = "(Optional) Map of resource tags for all AWS resources. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level."
  type        = map(string)
  default     = {}
}

variable "client_cidr_block" {
  type        = string
  description = "CIDR Block used for assigning IP's to clients, must not overlap with any of the connected networks."
}

variable "server_certificate_arn" {
  type        = string
  description = "ARN of the ACM certificate the server will use."
}

variable "cloudwatch_log_group_name" {
  type        = string
  description = "(Optional) CloudWatch log group name for VPN connection logging."
  default     = ""
}

variable "cloudwatch_log_stream_name" {
  type        = string
  description = "(Optional) CloudWatch log stream name for VPN connection logging."
  default     = ""
}

variable "auth_rules" {
  type = list(object({
    cidr        = string
    groups      = list(string)
    description = string
  }))
  description = "List of CIDR blocks, and IDP groups to authorize access for."
}

variable "private_subnets" {
  type        = list(string)
  description = "List of private subnets"
}

variable "vpc_id" {
  type        = string
  description = "VPC ID For the VPN SG"
}

variable "split_tunnel" {
  default     = false
  type        = bool
  description = "To split the VPN tunnel, or not, defaults to false"
}

variable "dns_servers" {
  type        = list(string)
  default     = []
  description = "(Optional) Information about the DNS servers to be used for DNS resolution. A Client VPN endpoint can have up to two DNS servers. If no DNS server is specified, the DNS address of the connecting device is used."
}
